### ISSUE TITLE
Create a Texture pack

### ISSUE THREAD

**Issue by manuelkoso** [peiva-git/SDM_project#102]

**Comment by manuelkoso** [comment]
Just two notes:
- If we want an [automatic packing](https://libgdx.com/wiki/tools/texture-packer#automatic-packing), this can be done only for the desktop version (see also [doc](https://libgdx.com/wiki/tools/texture-packer#from-source) and [dependency](https://libgdx.com/wiki/articles/dependency-management-with-gradle#tools-gradle)). So instead, the textures packaging can be done separately either with the GUI tools ([Texture Packer GUI](https://github.com/crashinvaders/gdx-texture-packer-gui) or [Skin Composer](https://github.com/raeleus/skin-composer)) or with terminal commands ([see](https://libgdx.com/wiki/tools/texture-packer#packing)).  
- We have only two images (the two circles) in the `assets` folder, the rest of the textures are built in the `GameScreen` class (the board squares). So, we have to add into the `asset` directory an image of a light board square and an image of a black board square and than using the  [Skin Composer](https://github.com/raeleus/skin-composer) (or `gdx.jar` and `gdx-tools.jar` by using the terminal) in order to package the skin and the 4 images all together. 

Does it make sense to do it for our small application? Let me know

**Comment by peiva-git** [comment]
We only need an image of a white square and two images for the two different kinds of `Stone`s. I'd use the [Texture Packer GUI](https://github.com/crashinvaders/gdx-texture-packer-gui) tool, since it looks like it's the simplest one. A texture package is particularly useful in our case, otherwise we need to manually manage the `dispose()`-ing of the textures, which is becoming increasingly tricky with the refactoring.

**Comment by manuelkoso** [comment]
We can close this issue I think.

**Comment by peiva-git** [comment]
Yup

**Comment by peiva-git** [comment]
Closed by #107
