### ISSUE TITLE
`FreedomBoardStatusObserver` tests

### ISSUE THREAD

**Issue by manuelkoso** [peiva-git/SDM_project#115]
We have to add some tests for the `FreedomBoardStatusObserver` class.

**Comment by peiva-git** [comment]
The `FreedomBoardStatusObserver` class relies implicitly on the game status as well (as the name implies) since we need the players to determine the current state. Therefore, we either make the design choice to return a `Color` instead of a `Player` in the `getCurrentWinner` method, or the `FreedomBoardStatusObserver` can't be tested outside of a game environment

**Comment by manuelkoso** [comment]
Yes, you are right. We can close this issue then.
